### ISSUE TITLE
Monorepos?

### ISSUE THREAD

**Issue by nandorojo** [software-mansion/radon-ide#129]
Hey, should this work in a monorepo, or do I have to open the `expo` package directly in VSCode?

**Comment by phuongnn1996** [comment]
> > After adding `launch.json` with the correct `appRoot` it's now finding the project properly:
> > ```
> > Check pods in /Users/simonreggiani/dev/cook-universal/apps/expo/ios /Users/simonreggiani/dev/cook-universal/apps/expo
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But it's stuck at `Building using "xcodebuild ...` for 50 minutes now.
> > It's stuck at `GatherProvisioningInputs` in the builds logs.
> 
> How do you set the root to get it to work? I have the same structure, but the IDE always detecting my monorepo root as the app root.
> 
> ```
> 2024-05-04 15:52:08.409 [error] Found multiple **/metro.config.{js,ts} files in the workspace
> 2024-05-04 15:52:08.550 [error] Found multiple **/app.config.{js,ts} files in the workspace
> 2024-05-04 15:52:09.204 [info] Found app root folder: /Users/idrakimuhamad/devs/tesla-mbk
> ```
> 
> The app should be inside `apps/expo`.

Restart VS Code should make it apply your change.
