### ISSUE TITLE
Button to reload the app?

### ISSUE THREAD

**Issue by terrysahaidak** [software-mansion/radon-ide#145]
There is this "Reset the app" button next to the url bar, i was expecting it to just close the app and open again, but looks like it does the whole new build which takes 2m+ for me.

<img width="288" alt="image" src="https://github.com/software-mansion/react-native-ide/assets/7809008/238739c4-1f0a-4546-86c1-48af7b5f7db0">

But it's very common (at least for me) to close the app and open again since fast refresh and reload doesn't always work properly.

Do you have any plans for such a convenient button to just reload the app completely so i can see the splash screen again?

**Comment by jakub-gonet** [comment]
We'd also like to add an option to have fine-grained controls over reload – “reload JS”, “restart app process”, “clean build”, “reinstall app”. It shouldn't replace the button but exist as an additional feature.
