### ISSUE TITLE
Stuck on spinner when IDE failed to start the first time

### ISSUE THREAD

**Issue by wojtekmaj** [software-mansion/radon-ide#174]
Here's what I did:
- I installed RNIDE (before installing Android Emulator)
- RNIDE complained about it when I ran diagnosis
- I installed Android Emulator
- Re-ran diagnosis, this time everything was in order
- On the main screen, can't remember if I clicked some kind of "retry" or not
- Got stuck on a page showing just the spinner

Closing RNIDE and opening it again fixed the issue and I was met with the screen offering me to create device.

**Comment by filip131311** [comment]
Fixed with #563
