### ISSUE TITLE
Cannot run project; RCTThirdPartyFabricComponentsProvider.h: No such file

### ISSUE THREAD

**Issue by subtleGradient** [software-mansion/radon-ide#187]
This project builds and runs normally using expo. With react-native-ide, it fails.

Here's my full log:
https://gist.github.com/subtleGradient/56e4dc1328b3c331a8976dd92378297a

This seems like the relevant line:

```
2024-05-01 08:13:57.252 [info] error: /Users/tom/Projects/frens-v4/node_modules/react-native/React/Fabric/RCTThirdPartyFabricComponentsProvider.h: No such file or directory (in target 'React-RCTFabric' from project 'Pods')
```

**Comment by messabih-khalil** [comment]
> This project builds and runs normally using expo. With react-native-ide, it fails.
> 
> Here's my full log: https://gist.github.com/subtleGradient/56e4dc1328b3c331a8976dd92378297a
> 
> This seems like the relevant line:
> 
> ```
> 2024-05-01 08:13:57.252 [info] error: /Users/tom/Projects/frens-v4/node_modules/react-native/React/Fabric/RCTThirdPartyFabricComponentsProvider.h: No such file or directory (in target 'React-RCTFabric' from project 'Pods')
> ```

how you solved this problem ?
