### ISSUE TITLE
DebugAdapter does not receive console api calls properly

### ISSUE THREAD

**Issue by matinzd** [software-mansion/radon-ide#206]
## Description

Debug adapter websocket connection is not receiving the complete log in the buffer for type `Runtime.consoleAPICalled`.

## Environment

React Native IDE: 0.0.9
React Native: 0.74.0

**Comment by kmagiera** [comment]
this is an old report and we've made a number of improvements to console API handling since then. I'll close this one but in case you're experiencing some issues in that area please comment and we will create new issue or open this one back.
