### ISSUE TITLE
Improve developer experience with in-app language switching

### ISSUE THREAD

**Issue by harshilparmar** [software-mansion/radon-ide#313]
**Description**
Currently, testing translations within the React Native IDE requires manually switching the device system language. This can be cumbersome and disrupts workflow.

This pull request proposes adding a dedicated in-app setting to easily switch the language used by the application during development. This will significantly improve developer experience by:
- Reducing context switching and wasted time.
- Allowing for more efficient translation testing.

I'm excited to contribute this feature and would be happy to address any feedback or questions.

![Screenshot 2024-05-27 at 10 50 30 AM](https://github.com/software-mansion/react-native-ide/assets/45915468/7557f8c4-1c7e-46cf-920e-6cbd39cad1b2)

**Comment by kmagiera** [comment]
In #590 and #532 we added "Localization" device setting. I'm assuming it covers the functionality you're requesting here so will close this one. In case you had something different in mind, please let us know and we will reopen.
