### ISSUE TITLE
Unable To Load iOS Simulator

### ISSUE THREAD

**Issue by yasir-a** [software-mansion/radon-ide#331]
**Description*
Just testing React Native IDE.
When clicking "Add iPhone" button, the iOS simulator doesn't get load. Please check the unending "loading spinner" in attached screenshot.

**Environment**
- macOS Sonoma: 14.3.1 (23D60)
- Version of React Native: 0.74.1
- Xcode 15
- VsCode: 1.89.1 (Universal)
- React Native IDE: v0.0.14-beta
- Android Studio Version: 2023.2 (AI-232.10300.40.2321.11668458)

<img width="568" alt="Screenshot 2024-05-30 at 17 05 22" src="https://github.com/software-mansion/react-native-ide/assets/62054130/6a128ae1-48cc-4147-87ee-1ecd0f5b7dc1">

**Comment by filip131311** [comment]
Hello, thank you for the feedback,
would you mind providing iOS versions installed on your mac? 

You can find them in xcode, by going into settings - > platforms

Also I believe it is a duplicate of #314
