### ISSUE TITLE
Stuck in waiting for the app to load

### ISSUE THREAD

**Issue by wcastand** [software-mansion/radon-ide#383]
**Description*
Launching the expo app and stuck in Waiting for the app to Load, the stream link shows that it's stuck on the notification alert request access.

**Environment**
- v0.0.15
- Expo 51

**Comment by kmagiera** [comment]
Can you try following the instructions here to provide more logs and details on whats going on? https://ide.swmansion.com/docs/troubleshooting

Also, in the "waiting for app to load" stage, you can click on that text to see what's going on the simulator screen despite the fact IDE didn't detect the process app to finish booting

**Comment by salieflewis** [comment]
Interesting, for me clicking "Waiting for app to load" brought me to a view where it is now actually rendering the screen.

**Comment by kmagiera** [comment]
As this is duplicate, I'll be closing in favor of #633 that tracks this issue for a much more recent version
