### ISSUE TITLE
Android Emulator stopped working

### ISSUE THREAD

**Issue by monarcode** [software-mansion/radon-ide#493]
**Description*
After i accidentally tried running 2 instances, android emulator seems to no longer be working

i have rebooted my machine, reinstalled vscode, reinstalled RN IDE plugin, nothing works.

https://github.com/user-attachments/assets/60f020a3-9772-4553-b04a-809034758e80

Please help

**Environment**
- Version of currently used React Native IDE - v0.0.16
- Version of React Native/Expo used in the project. - RN 0.74.5, Expo sdk
- Any other versions of tools related to the problem.

**Comment by jakub-gonet** [comment]
Please add logs from build and extension logs. Also, you can try recreating emulator and seeing if it helps.

**Comment by jakub-gonet** [comment]
This issue was not active for some time so I'm closing it.
If you need further help please reply or create a new issue.
