### ISSUE TITLE
Stuck on "waiting for app to load" forever 

### ISSUE THREAD

**Issue by nichol6s** [software-mansion/radon-ide#544]
**Description*
The app build and runs normally but when I'm trying to use the extension it stucks on "waiting for app to load" forever. I already tried reinstalling, restarting vscode, updating packages, rolling back to old packages version etc. 

**Environment**
-  React Native IDE version: 0.0.18
-  React Native: 0.74.1
-  Expo: 51.0.8

**Comment by tjvanderende** [comment]
Same versions & issue unfortunely. Was excited to try the tool

**Comment by tuguScript** [comment]
Same issue here. The app hangs at "waiting for app to load" with the extension version v0.0.19. Hope this gets resolved soon.

**Comment by alberto-dinca** [comment]
> Same issue here. The app hangs at "waiting for app to load" with the extension version v0.0.19. Hope this gets resolved soon.

Same issue for me also

**Comment by kmagiera** [comment]
Thanks for reporting. Please take a look at the troubleshooting section and try to provide some additional details for this issue. Otherwise there's very little we can do. Check out this guide to learn how to see/collect logs: https://ide.swmansion.com/docs/troubleshooting

**Comment by tjvanderende** [comment]
Yeah so it also happens with a newly setup expo project using `npx create-expo-app@latest`. 
Versions used:
    "expo": "~51.0.28",
    "react-native": "0.74.5",
with radon version 0.0.19 running on Windows 11. Trying to run on the Google Pixel 6 simulator.
The output inside the terminal provided by the extension:
`024-10-02 18:27:40.283 [info] Will wait for app ready and for preview
2024-10-02 18:27:40.284 [info] Launch preview c:\Users\tjvan\.vscode\extensions\swmansion.react-native-ide-0.0.19\dist\sim-server-executable.exe android,--id,emulator-5556
2024-10-02 18:27:40.699 [info] sim-server: [2024-10-02T16:27:40Z INFO  simulator_server::mjpeg_server] MJPEG server started at http://127.0.0.1:61448/stream.mjpeg
2024-10-02 18:27:40.699 [info] Stream ready http://127.0.0.1:61448/stream.mjpeg
2024-10-02 18:27:40.699 [info] sim-server: stream_ready http://127.0.0.1:61448/stream.mjpeg`

**Comment by PEZO19** [comment]
Same. Even the logs do not show up (as read on troubleshooting page). Basically the whole is frozen and I just can't use.

**Comment by je2ryw** [comment]
Same issue here, for now, set configurations.preview.waitForAppLunch as false in the launch.json as a workaround. But Inspect and Preview are not working. I guess due to "RNIDE_appReady" event never received.

* Radon 0.0.19
* Cursor 0.41.3
* Expo 51.0.32
* React Native 0.74.5

`
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "radon-ide",
      "request": "launch",
      "name": "Radon IDE panel",
      "ios": {},
      "android": {
        "buildType": "debug"
      },
      "appRoot": ".",
      "isExpo": true,
      "preview": {
        "waitForAppLaunch": false
      }
    }
  ]
}
`

**Comment by je2ryw** [comment]
> Same issue here, for now, set configurations.preview.waitForAppLunch as false in the launch.json as a workaround. But Inspect and Preview are not working. I guess due to "RNIDE_appReady" event never received.
> 
> * Radon 0.0.19
> * Cursor 0.41.3
> * Expo 51.0.32
> * React Native 0.74.5
> 
> `{ "version": "0.2.0", "configurations": [ { "type": "radon-ide", "request": "launch", "name": "Radon IDE panel", "ios": {}, "android": { "buildType": "debug" }, "appRoot": ".", "isExpo": true, "preview": { "waitForAppLaunch": false } } ] }`

Quick update here, my "waiting for app to load" issue resolved after upgrade the dependency react-native-root-siblings@5.0.1. The old 4.x version has `setWrapperComponentProvider` usage which is conflicting with Radon IDE.

**Comment by tjvanderende** [comment]
@je2ryw thnx for the tip. I don't use the library, but probably its something like this for me as well. The hard part is, is how to debug this. I couldn't find any detailed error reported by Radon IDE. How did you find out that this was your issue?

**Comment by je2ryw** [comment]
> @je2ryw thnx for the tip. I don't use the library, but probably its something like this for me as well. The hard part is, is how to debug this. I couldn't find any detailed error reported by Radon IDE. How did you find out that this was your issue?

You can try `grep -R setWrapperComponentProvider *` in the `node_modules` directory to see beside `react-native`, `react-native-web`, `expo-dev-launcher` or `expo-dev-menu`, if there are any other dependency libraries are using `setWrapperComponentProvider`.

**Comment by nateyeazel** [comment]
Thanks for the tips, adding "waitForAppLaunch": false let me get past the "waiting for app to load" screen as well, but as you both noted the inspector doesn't work and I'm getting the error "Couldn't connect to debugger". I ran `grep -R setWrapperComponentProvider * ` but the only usages were in react-native, react-native-web, expo-dev-launcher or expo-dev-menu. 

The only issues I can see in the output from Radon are "[error] Couldn't connect to debugger" and "[warning] Too many callbacks in memory! Something is wrong!" when I try to inspect. In the debug console it does say "An error occurred while attaching debugger to the application. Unable to start ios_webkit_debug_proxy: Error: spawn ios_webkit_debug_proxy ENOENT (error code 1410)"

**Comment by bessim-dev** [comment]
here is the error i got:
2024-10-12 21:34:28.466 [error] Unable to resolve module __RNIDE_lib__/expo_router_plugin.js from /Users/x/Code/x/node_modules/expo-router/entry.js: __RNIDE_lib__/expo_router_plugin.js could not be found within the project or in these directories:
  node_modules
  ../../node_modules
  node_modules
  ../../node_modules
  node_modules/react-native/node_modules
  /Users/x/.vscode/extensions/swmansion.react-native-ide-0.0.19/lib/expo_router_plugin.js
   9 | // should be added here.
  10 | renderRootComponent(App);
> 11 |
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
