### ISSUE TITLE
JAVA_HOME is set to an invalid directory

### ISSUE THREAD

**Issue by abdul-razaq** [software-mansion/radon-ide#545]
**ERROR*
I keep getting the error below when I try to boot up the Android emulator in the react native IDE.

**ERROR: JAVA_HOME is set to an invalid directory: C:\Program Files\Android\Android Studio\jbr
Please set the JAVA_HOME variable in your environment to match the 
2024-09-14 15:34:47.193 [info] location of your Java installation. **

This error occurs even tho my JAVA_HOME points to the right java installation and works well when opening my emulator in the normal usual way.

**Environment**
- Version 0.0.18
- React native 0.74.5.
- Expo: ~51.0.31
- Java version "17.0.11" 2024-04-16 LTS, Java(TM) SE Runtime Environment (build 17.0.11+7-LTS-207), Java HotSpot(TM) 64-Bit Server VM (build 17.0.11+7-LTS-207, mixed mode, sharing).

**Comment by cacacaio** [comment]
I have the same issue on windows, the env variable is working if I print it via powershell and cmd. But on IDE it always points to C:\Program Files\Android\Android Studio\jbr

What I did as a workaround is copy all the JDK files to this folder so at least it works, but it would be good to have a permanent fix

**Comment by abdul-razaq** [comment]
Actually, this worked for me. I hope there is a permanent fix for this as soon as possible. Thank you!

**Comment by p-malecki** [comment]
Hi, thanks for reporting. Radon uses JAVA_HOME env var, so there's no need for workarounds from now on.
