### ISSUE TITLE
Simulator server binary not found

### ISSUE THREAD

**Issue by kewinzaq1** [software-mansion/radon-ide#576]
Since the recent release, the simulator files do not include release hash, and it causes the issue 
```
`Simulator server binary not found: dist/sim-server-Release-7602d2da18239a04b743cb6917358b18e74c7168

Make sure to follow development setup instructions: https://ide.swmansion.com/docs/development
You can download the binary from the releases page on GitHub: https://github.com/software-mansion/radon-ide/releasesz
```
Is this script up to date? Should the build script be updated, or just the attached files should be renamed?

**Comment by kmagiera** [comment]
This was our fault. We still want the name to contain the hash. Will update the attachments from the release later today. Thanks for reporting!

**Comment by kmagiera** [comment]
This is fixed now.
