### ISSUE TITLE
IDE panel - The word "IDE" is repeated in the sidebar tab title

### ISSUE THREAD

**Issue by maciejtrabkaswm** [software-mansion/radon-ide#58]
**Tested on:**
pull 29.03 14:00
Apple M1 Pro, macos 13.5.2
RandomQuotes app

**Step to reproduce:**
Click: Gear icon(settings) -> Change IDE panel location -> Side panel

**Description:**
The word "IDE" is repeated in the sidebar tab title: ‘React Native IDE: IDE Panel’
It can be: ‘React Native IDE Panel’

![image](https://github.com/software-mansion/react-native-ide/assets/97039352/058d5290-680d-455b-9532-9a8efb0f9421)

**Comment by filip131311** [comment]
solved
