### ISSUE TITLE
EAS: Unhandled promise rejection Could not find Xcode project files

### ISSUE THREAD

**Issue by mikecfisher** [software-mansion/radon-ide#610]
**Description**
I have a brand new test expo app that I installed and am trying to use Radon. I configured my app to do development builds via EAS. I followed the docs but I keep getting this error in the build logs. 

```
2024-10-10 22:48:38.949 [error] Command pod install execution resulted in an error: A system error occurred (Command failed with ENOENT: pod install
spawn pod ENOENT)
2024-10-10 22:48:38.949 [error] Pods not installed A system error occurred (Command failed with ENOENT: pod install
spawn pod ENOENT)
2024-10-10 22:48:38.959 [error] Couldn't start device session Could not find Xcode project files in "/Users/mike/dev/ludex/pizza-app/ios" folder
2024-10-10 22:48:38.959 [error] Unhandled promise rejection Could not find Xcode project files in "/Users/mike/dev/ludex/pizza-app/ios" folder
2024-10-10 22:48:59.813 [error] Unhandled promise rejection Client not initialized
```

My Launch config looks like this. I should note that my editor warns me that "Property eas is not allowed."
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "radon-ide",
      "request": "launch",
      "name": "Radon IDE panel",
      "isExpo": true,
      "eas": {
        "ios": {
          "profile": "development",
        },
        "android": {
          "profile": "development",
          "buildUUID": "40466d0a-96fa-5d9c-80db-d055e78023bd"
        }
      }
    }
  ]
}
```
I am using Cursor and installed the extension directly from the releases page. 
I see the docs updated for EAS and that PR was merged last week, however on the releases page it seems the most recent release is 2 weeks ago. Could it be that EAS support isn't part of the current release even though it's mentioned in the docs?

Also for Diagnostics everything gets a green check except for "Pods" "unable to install pods" but that is because I don't have an ios folder I believe. Also the app builds and runs fine via Expo. 

**Environment**

- Version of currently used Radon IDE : v0.0.19
- Version of React Native/Expo used in the project.
```
    "react-native": "0.74.5",
    "expo": "~51.0.28",
    ```
- Any other versions of tools related to the problem.

**Comment by kmagiera** [comment]
yes, sorry, the EAS support got merged earlier and it went out as part of the docs update while we only published the updated version of the IDE today. Can you try the new version and re-open if the problem persist?
