### ISSUE TITLE
Cannot run project

### ISSUE THREAD

**Issue by featlast** [software-mansion/radon-ide#613]
**Description**

**Environment**

At the moment I have a project with expo go, and I can't run the project, Expo, "expo": "~51.0.37",   "react-native": "0.74.5","react": "18.2.0",
![image](https://github.com/user-attachments/assets/0fae15c0-2246-4342-835c-00763b3a6162)
![image](https://github.com/user-attachments/assets/5cb768b3-1b9c-4a7e-8e03-924c885b6a3f)

**Comment by divineniiquaye** [comment]
Kindly navigate to the OUTPUT section in the VSCode from terminal and select Radon IDE, my failed due to npm install not recognizing that `workspace:*`.

Unfortunately am unable to change it to use pnpm

**Comment by mikehuebner** [comment]
See this as well

```
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*
```

**Comment by kmagiera** [comment]
Wonder if #735 could fix this issue. In the worst case #725 adds a configuration option where you can override the detected package manager. This should allow you to specify "pnpm" in the IDE settings in case it has issues detecting the package manager
