### ISSUE TITLE
"Cannot run project" when IDE is windowed, but project runs fine

### ISSUE THREAD

**Issue by arnaud9145** [software-mansion/radon-ide#632]
**Description**
Just started using Radon IDE on an existing project. I prefer to use the IDE windowed because I'm used to close all active tabs using cmd + k + w. But in windowed state, the IDE shows an error "Cannot run project Run diagnostics to find out what went wrong."
![Capture d’écran 2024-10-16 à 18 53 16](https://github.com/user-attachments/assets/112d212b-61c4-4243-8350-e6fdea7cf73e)

If I go to diagnostics : 
![Capture d’écran 2024-10-16 à 18 53 45](https://github.com/user-attachments/assets/62f65f46-8b6e-45a4-ad79-55d3304405ab)
(I do not use android emulator)

If I do not use the IDE windowed, I do not have errors: 
![Capture d’écran 2024-10-16 à 18 56 18](https://github.com/user-attachments/assets/648e3a65-d620-4198-82a3-082653d1b3c2)

Note : it's just an error message, everything seems to be working anyway

Thanks for this tool :) 

**Environment**

- Radon IDE : 0.0.20
- React Native : 0.74.0 without expo
- Yarn : 1.22.22
- node : 20.15.1

**Comment by kmagiera** [comment]
in 0.21 we reworked the diagnostics logic, would you be able to test this on the newest release.

Also to clarify: by "windowed" you mean that the IDE is in detached window rather than in side panel or in separate tab, right?

**Comment by arnaud9145** [comment]
Yes that's right, panel location is "Editor tab", and then the tab is extracted from vs code into a dedicated window, that's what I called windowed.

I just tested in 0.21, seems to work. Since I created the issue, I discovered the "side panel" mode, and it's perfect for me, I did not find it at first. But now if someone need it windowed its possible :)

Thanks !
