### ISSUE TITLE
Could not run project

### ISSUE THREAD

**Issue by arunesh-singh** [software-mansion/radon-ide#646]
1. Its taking about 10 mins to start.
2. After diagnosis getting error node modules aren't installed.

**Comment by kmagiera** [comment]
Thanks for reporting. Can you check out the troubleshoooting guide https://ide.swmansion.com/docs/troubleshooting and specifically the section about obtaining logs. Then attach those logs to your report. We'd also like to know what version of RN/Expo your project is using
