### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by kmagiera** [software-mansion/radon-ide#688]
We are open to external contributors willing to work on adding Linux support. This issue is created to provide some initial guidance.

**Read development setup guide**

Start by getting yourself familiarized with development environment setup for the IDE:
https://ide.swmansion.com/docs/development

This guide covers a number of topics relevant to all platforms.

**Simulator server builds**
We recently started publishing linux builds for simulator server. This should make the "Prepare simulator server build" step work out of the box on Linux, but in case it doesn't you can manually download pre-built linux binaries from [releases page](https://github.com/software-mansion/radon-ide/releases/tag/v0.0.21-beta).

**Where to start making changes**

In Radon IDE 0.18 we added experimental Windows support. We suspect, that adding support for linux should have similar scope. You may want to check the PR where Windows support landed: #462 but mainly look around for changes where platform-specific branching is implemented using `Platform` module. On top of that, we may also have some platform-compatibility checks to notify people Linux isn't supported – so relaxing those checks may also be a necessary step.

**Comment by lypanov** [comment]
Is this somehow related to the fact that my Cursor on Windows setup with WSL2 (yes, I'm testing all your corner cases here sorry) isn't even detecting the workspace? (as in, no Radon IDE features are enabled). I'm not sure how many people even use a setup like mine honestly.

**Comment by lypanov** [comment]
That one greets me with: 

![image](https://github.com/user-attachments/assets/478d4bcb-d0f2-4cf8-b66a-652b6c02bf82)
