### ISSUE TITLE
does not work with pnpm workspaces

### ISSUE THREAD

**Issue by AyoCodess** [software-mansion/radon-ide#736]
We have a similar error with the use of  ``catalog:``` to reference node modules versions. 
![Screenshot 2024-11-17 at 15 41 17](https://github.com/user-attachments/assets/2b890701-636e-47c7-b32a-b2a78858bcf1)

**Comment by maciekstosio** [comment]
Hi, thanks for the bug report. Could you please provide a repo with a reproduction? I'll try to take a look at it.
