### ISSUE TITLE
Stuck on boot

### ISSUE THREAD

**Issue by YadwinderSingh48** [software-mansion/radon-ide#759]
**Description**
I launch the IDE but it Stucks on Booting device for too long (around 30mins). I have tried re launch re installation but stills the same issue.

**Environment**
I'm using a windows machine.
The Radon IDE version is v0.0.22.
The project is on react native cli and using the VS Code.

**Comment by maciekstosio** [comment]
Thanks for reporting. Did you check the diagnostics panel if everything is set up properly? 
<img width="258" alt="image" src="https://github.com/user-attachments/assets/c9837ac3-564b-4948-aac5-5ae1fef0c71d">
Could you provide us with logs? You can find them in `Output > Radon IDE`:
<img width="597" alt="image" src="https://github.com/user-attachments/assets/5265ca62-5ec8-4ab7-9176-2837024b6b3c">

**Comment by YadwinderSingh48** [comment]
Hey, in diagnostics expo, expo router and storybook options has cross mark, that's because may be my project is not in the expo.

I just noticed when I open android studio there is an emulator running already with the same name Pixel9 which is selected in the IDE Panel but in Panel device still shows booting device and stuck there

**Comment by maciekstosio** [comment]
> expo, expo router and storybook options has cross mark
