### ISSUE TITLE
Can't change appearance Expo Dev Client 50 

### ISSUE THREAD

**Issue by maciekstosio** [software-mansion/radon-ide#776]
**Description**

Can't change appearance. I'm getting logs below in Radon IDE Output:

```
2024-11-26 16:53:20.419 [info] sim-server: video_error replay not found
2024-11-26 16:53:20.420 [info] sim-server: [2024-11-26T15:53:20Z WARN  simulator_server::media_handler] Failed to stop video with id "replay" as it was not found
```

**Environment**
- both iOS/Android
- IDE 0.24-beta
- react-native 0.73.6
- expo 50.0.14

**Steps to reproduce**
- run `test-apps/expo-dev-client-50` 
- change apperence 
- nothing happens - it should change light/dark mode 

<video src="https://github.com/user-attachments/assets/aeedbc3d-3b7f-4460-8334-ce6a1594af8a" />

**Comment by p-malecki** [comment]
The same issue occurs  on Windows.

**Comment by maciekstosio** [comment]
|Android|iOS|
|-|-|
|<video src="https://github.com/user-attachments/assets/df5fd39f-da50-48f7-af91-bf25c3b504d1" />|<video src="https://github.com/user-attachments/assets/1ba765a7-a1e4-439b-85f0-5741b07c0e67" />|

Seems like a problem with React Native not the IDE
