### ISSUE TITLE
It's hard to remove device in narrow side panel 

### ISSUE THREAD

**Issue by maciekstosio** [software-mansion/radon-ide#778]
**Description**

It's hard to remove the device in the narrow side panel. The dialog is cut from both sides, although there is some free space left that potentially could be used and the avf name could be truncated. Users can work around it by just expanding the IDE Panel.

<img width="1223" alt="deleting device small screen" src="https://github.com/user-attachments/assets/ef36b64a-d5e7-4f5f-ae34-312fb479f5cc">

**Environment**

- react-native 73.6
- expo 50 dev client
- radon ide 0.24-beta

**Comment by p-malecki** [comment]
This issue has been resolved in #767.
