### ISSUE TITLE
Does not work in monorepo codebases

### ISSUE THREAD

**Issue by jcgertig** [software-mansion/radon-ide#821]
**Description**
The activation settings make it so that this does not work in a monorepo
If it was a glob workspaceContains:**/metro.config.ts would work or better yet config setting to choose

**Environment**

- Version of currently used Radon IDE (Extensions tab -> click on Radon IDE extension -> version is located next to the extension name) 1.0.0

**Comment by maciekstosio** [comment]
Hi, thanks for reporting. Could you provide more details about your setup? You should be able to run it from the workspace root (in case of multiple apps, one of them will be chosen, unless [configured with appRoot in launch.json](https://ide.swmansion.com/docs/guides/configuration#other-settings)).

**Comment by jcgertig** [comment]
<img width="414" alt="Screenshot 2024-12-03 at 11 06 35 AM" src="https://github.com/user-attachments/assets/74bc8148-de57-4205-9192-e73d8cb14ff1">
<img width="746" alt="Screenshot 2024-12-03 at 11 05 01 AM" src="https://github.com/user-attachments/assets/b11303ac-95ce-4018-a2e2-92e2285d8bb0">

**Comment by jcgertig** [comment]
So I was able to launch via Radon IDE: Diagnostics but that's it no other options seem to work for me

**Comment by kmagiera** [comment]
Thanks @jcgertig for this report. Would you be able to share some sample repo with similar structure and configuration that we could use to reproduce this issue?

**Comment by jcgertig** [comment]
Thanks @maciekstosio and @kmagiera for the help

**Comment by jcgertig** [comment]
@kmagiera any idea when this will be ready?

**Comment by kmagiera** [comment]
@jcgertig we plan to publish an update next week that'd include this and other changes. If you'd like I can build a .vsix file for you to install and try locally before then.

**Comment by jcgertig** [comment]
That could be helpful unfortunately the above #830 has bricked to extension for me currently
